server:
  port: 9090

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://36.112.65.110:3306/bimvrserver?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: Jhkj13911822521
    filters: wall,mergeStat
    data-source-name: beta
  redis:
    host: 127.0.0.1
    port: 6379
    password: bimvr55@
logging:
  config: classpath:log/logback-spring.xml
  path: F:/log/bimvr

##文件跟路径
alipay_cert_file_path: C:/Program Files/workspace/bimvr/src/main/resources/

#FTP配置信息
host: 36.112.65.110
prot: 21
username: Administrator
password: Jhkj73630915


